version: "3"
services:
  identitypostgre:
    build: .
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80

  identitypostgre_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=blazoridentity2
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    
  proxy:
    image: nginx:latest
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - "80:80"
        - "443:443"  


